name: rime_env
channels:
  - conda-forge
  - dglteam
dependencies:
  # - numpy>=1.9.*
  # - numpydoc>=0.7.0
  # - scipy>=0.19.*
  # - scikit-learn>=0.24.2
  # - pandas>=1.1.5
  # - swig>=4.0.0
  # - pytorch>=1.7.1
  # - lightfm>=1.16
  # - numba>=0.52.0
  # - matplotlib>=3.3.4
  - pytest
  - dgl  # use dgl-cu111 for gpu access
  - implicit  # install implicit-proc=*=gpu from conda for gpu access
  # - dataclasses  # backport from python3.7
  # - backports.cached-property  # backport from python3.8
  # - setuptools_scm
  # - seaborn>=0.11.1
