name: rime36
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy>=1.9.*
  - numpydoc>=0.7.0
  - scipy>=0.19.*
  - scikit-learn>=0.24.2
  - pandas>=1.1.5
  - swig>=4.0.0
  - pytorch>=1.7.1
  - lightfm>=1.16
  - numba>=0.52.0
  - matplotlib>=3.3.4
  - flake8
  - pytest
  - implicit
  - dataclasses # backport from python3.7
  - backports.cached-property
